MINE = -1 #15
BLAST = -2 #14
WRONGFLAG = -3 #13
UNFLAGGED = -4 #12
COVERED = 9 #
DOWN = 10 #
FLAGGED = 11 #

# MINE = 'M'
# BLAST = 'B'
# WRONGFLAG = 'W'
# UNFLAGGED = 'U'
# COVERED = 'C'
# DOWN = 'D'
# FLAGGED = 'F'